deploymentName: db-payment
serviceName: db-payment
appLabel: db-payment
appName: db-payment

replicaCount: 1

image:
  repository: mysql
  tag: 8.0

containerPort: 30622

service:
  port: 30622

pvc:
  name: payment-pvc
  
customEnvs:
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: PAYMENT_MYSQL_ROOT_PASSWORD
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: PAYMENT_MYSQL_DATABASE