deploymentName: db-instructor
serviceName: db-instructor
appLabel: db-instructor
appName: db-instructor

replicaCount: 1

image:
  repository: mysql
  tag: 8.0

containerPort: 30619

service:
  port: 30619

pvc:
  name: instructor-pvc
  
customEnvs:
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: INSTRUCTOR_MYSQL_ROOT_PASSWORD
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: INSTRUCTOR_MYSQL_DATABASE