deploymentName: service-qna
serviceName: qna
appLabel: qna
appName: qna

replicaCount: 1

hpa:
  name: qna-hpa
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

resources:
  cpu:
    request: "500m"
    limit: "1000m"
  memory:
    request: "1Gi"
    limit: "2Gi"

image:
  repository: martinms20/qna
  tag: cloud

containerPort: 14128

service:
  type: ClusterIP
  port: 14128
  targetPort: 14128

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
redis_enabled: true

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: QNA_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: QNA_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: QNA_SPRING_DATASOURCE_URL