deploymentName: eurekaserver-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: martinms20/eurekaserver
  tag: v1.0.0

containerPort: 14118

service:
  type: ClusterIP
  port: 14118
  targetPort: 14118

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
