deploymentName: db-authentication
serviceName: db-authentication
appLabel: db-authentication
appName: db-authentication

replicaCount: 1

image:
  repository: mysql
  tag: 8.0

containerPort: 30618

service:
  port: 30618

pvc:
  name: authentication-pvc

customEnvs:
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_MYSQL_ROOT_PASSWORD
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_MYSQL_DATABASE
