apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
  labels:
    app: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: martinms20/course:v1.0.0
          ports:
            - containerPort: 14120
          env:
            - name: SPRING_APPLICATION_NAME
              value: course
            - name: SPRING_PROFILES_ACTIVE
              value: development
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eurekaserver:14118/eureka/"
            #            - name: JAVA_TOOL_OPTIONS
            #              value: "-javaagent:/app/libs/opentelemetry-javaagent-1.27.0.jar"
            #            - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #              value: http://tempo:4317
            #            - name: OTEL_METRICS_EXPORTER
            #              value: none
#            - name: OTEL_SERVICE_NAME
#              value: "course"
            - name: AWS_ACCESS_KEY_ID
              value: "AKIA6GBMGQU2WPGRSEWD"
            - name: AWS_SECRET_ACCESS_KEY
              value: "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"
            - name: AWS_S3_REGION
              value: "ap-southeast-1"
            - name: AWS_S3_BUCKET
              value: "vocasia"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db-course:30620/course_db
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://configserver:14117/"
---
apiVersion: v1
kind: Service
metadata:
  name: course
spec:
  selector:
    app: course
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 14122
      targetPort: 14122
