deploymentName: enrollment-deployment
serviceName: enrollment
appLabel: enrollment
appName: enrollment

replicaCount: 1

hpa:
  name: enrollment-hpa
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75

resources:
  cpu:
    request: "256m"
    limit: "512m"
  memory:
    request: "256Mi"
    limit: "512Mi"

image:
  repository: martinms20/enrollment
  tag: cloud

containerPort: 14126

service:
  type: ClusterIP
  port: 14126
  targetPort: 14126

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
redis_enabled: true

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ENROLLMENT_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ENROLLMENT_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ENROLLMENT_SPRING_DATASOURCE_URL