global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "authentication"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["service-authentication:14120"]
  - job_name: "configserver"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["configserver:14117"]
  - job_name: "course"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["service-course:14122"]
  - job_name: "enrollment"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["service-enrollment:14126"]
  - job_name: "eurekaserver"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["eurekaserver:14118"]
  - job_name: "finance"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["service-finance:14127"]
  - job_name: "gatewayserver"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gatewayserver:14119"]
  - job_name: "instructor"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["service-instructor:14121"]
  - job_name: "order"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["service-order:14124"]
  - job_name: "payment"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "service-payment:14125" ]
  - job_name: "qna"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "service-qna:14128" ]