deploymentName: db-course
serviceName: db-course
appLabel: db-course
appName: db-course

replicaCount: 1

image:
  repository: mysql
  tag: 8.0

containerPort: 30620

service:
  port: 30620

pvc:
  name: course-pvc