server:
  port: 14122

spring:
  application:
    name: "course"
  profiles:
    active: "development"
  config:
    import: "optional:configserver:http://localhost:14117/"
  datasource:
    url: "jdbc:mysql://localhost:30626/vocasia_db"
    username: "root"
    password: "password"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 24MB
      max-request-size: 24MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:14118/eureka/

info:
  app:
    name: "course"
    description: "Course Service"
    version: "1.0.0"

logging:
  level:
    com:
      vocasia:
        course: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
