{
 "title": "1 testing",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Authentication CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"authentication\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"authentication\", area=\"heap\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Email CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"email\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Email Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"email\", area=\"heap\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instructor CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"instructor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instructor Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"instructor\", area=\"heap\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}