{
 "title": "3 - catalog service",
 "time": { "from": "2024-11-21T05:39:44.000Z", "to": "now" },
 "panels": [
  {
   "title": "Catalog CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"catalog\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalog Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"catalog\", area=\"heap\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Course CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"course\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Course Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"course\", area=\"heap\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instructor CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"instructor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instructor Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"instructor\", area=\"heap\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}