{
 "title": "4 - Instructor Testing",
 "time": { "from": "2024-11-21T08:33:47.000Z", "to": "now" },
 "panels": [
  {
   "title": "Instructor CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"instructor\"}",
     "legendFormat": "Instructor"
    }
   ]
  },
  {
   "title": "Instructor Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"instructor\", area=\"heap\"})/1024/1024",
     "legendFormat": "Instructor"
    }
   ]
  },
  {
   "title": "Authentication CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"authentication\"}",
     "legendFormat": "Instructor"
    }
   ]
  },
  {
   "title": "Authentication Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"authentication\", area=\"heap\"})/1024/1024",
     "legendFormat": "Instructor"
    }
   ]
  }
 ]
}