{
 "title": "6 - order service",
 "time": { "from": "2024-11-21T10:13:08.000Z", "to": "now" },
 "panels": [
  {
   "title": "Order CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"order\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Order Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"order\", area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Payment CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"payment\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Payment Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"payment\", area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Enrollment CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"enrollment\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Enrollment Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"enrollment\", area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Finance CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"finance\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Finance Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"finance\", area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}