{
 "title": "Vocasia Services Resource Usage",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Authentication CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{application=\"authentication\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"authentication\", area=\"heap\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalog CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{application=\"catalog\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalog Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"catalog\", area=\"heap\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Course CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{application=\"course\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Course Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"course\", area=\"heap\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Email CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{application=\"email\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Email Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"email\", area=\"heap\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enrollment CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{application=\"enrollment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enrollment Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"enrollment\", area=\"heap\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finance CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{application=\"finance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finance Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"finance\", area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Server CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{application=\"gatewayserver\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Server Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"gatewayserver\", area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instructor CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{application=\"instructor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instructor Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"instructor\", area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{application=\"order\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"order\", area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{application=\"payment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"payment\", area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}