deploymentName: db-finance
serviceName: db-finance
appLabel: db-finance
appName: db-finance

replicaCount: 1

image:
  repository: mysql
  tag: 8.0

containerPort: 30624

service:
  port: 30624

pvc:
  name: finance-pvc