deploymentName: order-deployment
serviceName: order
appLabel: order
appName: order

hpaLabel: order-hpa
hpaCpuUtilization: 50

memoryRequest: 512Mi
cpuRequest: 256m

memoryLimit: 1024Mi
cpuLimit: 512m

replicaCount: 2
maxReplicas: 5

image:
  repository: martinms20/order
  tag: v1.1.0

containerPort: 14124

service:
  type: ClusterIP
  port: 14124
  targetPort: 14124

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ORDER_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ORDER_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ORDER_SPRING_DATASOURCE_URL
  - name: FINANCE_PERCENT_PLATFORM_FEE
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: FINANCE_PERCENT_PLATFORM_FEE