global:
  configMapName: vocasia-configmap
  activeProfile: development
  configServerURL: configserver:http://configserver:14117/
  eurekaServerURL: http://eurekaserver:14118/eureka/
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/Vocasia/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-1.27.0.jar"
  otelExporterEndPoint: http://tempo-grafana-tempo-distributor:4317
  otelMetricsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092

  awsAccessKeyId: AKIA6GBMGQU2WPGRSEWD
  awsSecretAccessKey: 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
  awsS3Region: ap-southeast-1
  awsS3Bucket: vocasia

  midtransMerchantId: G831856510
  midtransClientKey: SB-Mid-client-4KbJJQfBaYS9Lplt
  midtransServerKey: SB-Mid-server-l-PGFhcZZ-wTh5bebWsEefs0
  midtransIsProduction: "false"

  authenticationApplicationName: authentication
  authenticationSpringDatasourceUsername: root
  authenticationSpringDatasourcePassword: password
  authenticationSpringDatasourceUrl: jdbc:mysql://db-authentication:30618/authentication_db
  authenticationOtelServiceName: authentication
  authenticationMysqlRootPassword: password
  authenticationMysqlDatabase: authentication_db

  courseApplicationName: course
  courseSpringDatasourceUsername: root
  courseSpringDatasourcePassword: password
  courseSpringDatasourceUrl: jdbc:mysql://db-course:30620/course_db
  courseOtelServiceName: course
  courseMysqlRootPassword: password
  courseMysqlDatabase: course_db

  enrollmentApplicationName: enrollment
  enrollmentSpringDatasourceUsername: root
  enrollmentSpringDatasourcePassword: password
  enrollmentSpringDatasourceUrl: jdbc:mysql://db-enrollment:30623/enrollment_db
  enrollmentOtelServiceName: enrollment
  enrollmentMysqlRootPassword: password
  enrollmentMysqlDatabase: enrollment_db

  financeApplicationName: finance
  financeSpringDatasourceUsername: root
  financeSpringDatasourcePassword: password
  financeSpringDatasourceUrl: jdbc:mysql://db-finance:30624/finance_db
  financeOtelServiceName: finance
  financeMysqlRootPassword: password
  financeMysqlDatabase: finance_db
  financePercentPlatformFee: 5

  instructorApplicationName: instructor
  instructorSpringDatasourceUsername: root
  instructorSpringDatasourcePassword: password
  instructorSpringDatasourceUrl: jdbc:mysql://db-instructor:30619/instructor_db
  instructorOtelServiceName: instructor
  instructorMysqlRootPassword: password
  instructorMysqlDatabase: instructor_db

  orderApplicationName: order
  orderSpringDatasourceUsername: root
  orderSpringDatasourcePassword: password
  orderSpringDatasourceUrl: jdbc:mysql://db-order:30621/order_db
  orderOtelServiceName: order
  orderMysqlRootPassword: password
  orderMysqlDatabase: order_db

  paymentApplicationName: payment
  paymentSpringDatasourceUsername: root
  paymentSpringDatasourcePassword: password
  paymentSpringDatasourceUrl: jdbc:mysql://db-payment:30622/payment_db
  paymentOtelServiceName: payment
  paymentMysqlRootPassword: password
  paymentMysqlDatabase: payment_db

  qnaApplicationName: qna
  qnaSpringDatasourceUsername: root
  qnaSpringDatasourcePassword: password
  qnaSpringDatasourceUrl: jdbc:mysql://db-qna:30625/qna_db
  qnaOtelServiceName: qna
  qnaMysqlRootPassword: password
  qnaMysqlRootPassword: qna_db

  gatewayserverApplicationName: gatewayserver
  gatewayserverOtelServiceName: gatewayserver

  keycloakAdmin: admin
  keycloakAdminPassword: admin
  keycloakLogLevel: DEBUG
  keycloakServerUrl: http://keycloak.default.svc.cluster.local:80
  keycloakClientId: vocasia-users
  keycloakClientSecret: "WzFldaxqCLxv01FH1Ovp9oeOKQ5NpDSn"
  keycloakRealm: Vocasia
  keycloakAuthClientId: vocasia-auth