deploymentName: db-vocasia-mysql
serviceName: db-vocasia-mysql
appLabel: db-vocasia-mysql
appName: db-vocasia-mysql

replicaCount: 1

image:
  repository: mysql
  tag: 8.0

containerPort: 30626

service:
  port: 30626

pvc:
  name: vocasia-mysql-pvc

customEnvs:
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: VOCASIA_MYSQL_ROOT_PASSWORD
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: VOCASIA_MYSQL_DATABASE
