apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: martinms20/payment:v1.0.0
          ports:
            - containerPort: 14125
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: PAYMENT_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: PAYMENT_SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: PAYMENT_SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: PAYMENT_SPRING_DATASOURCE_URL
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
#            - name: JAVA_TOOL_OPTIONS
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: JAVA_TOOL_OPTIONS
#            - name: OTEL_EXPORTER_OTLP_ENDPOINT
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: OTEL_EXPORTER_OTLP_ENDPOINT
#            - name: OTEL_METRICS_EXPORTER
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: OTEL_METRICS_EXPORTER
#            - name: OTEL_SERVICE_NAME
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: PAYMENT_OTEL_SERVICE_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: MIDTRANS_MERCHANT_ID
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: MIDTRANS_MERCHANT_ID
            - name: MIDTRANS_CLIENT_KEY
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: MIDTRANS_CLIENT_KEY
            - name: MIDTRANS_SERVER_KEY
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: MIDTRANS_SERVER_KEY
            - name: MIDTRANS_IS_PRODUCTION
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: MIDTRANS_IS_PRODUCTION
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 14125
      targetPort: 14125
