deploymentName: configserver-deployment
serviceName: configserver
appLabel: configserver
appName: configserver

hpaLabel: configserver-hpa
hpaCpuUtilization: 50

memoryRequest: 128Mi
cpuRequest: 256m

memoryLimit: 256Mi
cpuLimit: 512m

replicaCount: 1
maxReplicas: 2

image:
  repository: martinms20/configserver
  tag: v1.1.0

containerPort: 14117

service:
  type: ClusterIP
  port: 14117
  targetPort: 14117

appname_enabled: true
profile_enabled: false
config_enabled: false
discovery_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
