apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: martinms20/order:v1.0.1
          ports:
            - containerPort: 14124
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: ORDER_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: ORDER_SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: ORDER_SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: ORDER_SPRING_DATASOURCE_URL
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
#            - name: JAVA_TOOL_OPTIONS
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: JAVA_TOOL_OPTIONS
#            - name: OTEL_EXPORTER_OTLP_ENDPOINT
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: OTEL_EXPORTER_OTLP_ENDPOINT
#            - name: OTEL_METRICS_EXPORTER
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: OTEL_METRICS_EXPORTER
#            - name: OTEL_SERVICE_NAME
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: ORDER_OTEL_SERVICE_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: FINANCE_PERCENT_PLATFORM_FEE
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: FINANCE_PERCENT_PLATFORM_FEE
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 14124
      targetPort: 14124
