apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
  labels:
    app: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
        - name: gatewayserver
          image: martinms20/gatewayserver:v1.0.0
          ports:
            - containerPort: 14119
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: GATEWAYSERVER_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
#            - name: JAVA_TOOL_OPTIONS
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: JAVA_TOOL_OPTIONS
#            - name: OTEL_EXPORTER_OTLP_ENDPOINT
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: OTEL_EXPORTER_OTLP_ENDPOINT
#            - name: OTEL_METRICS_EXPORTER
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: OTEL_METRICS_EXPORTER
#            - name: OTEL_SERVICE_NAME
#              valueFrom:
#                configMapKeyRef:
#                  name: vocasia-configmap
#                  key: GATEWAYSERVER_OTEL_SERVICE_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
spec:
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 14119
      targetPort: 14119
