global:
  configMapName: vocasia-configmap
  mysqlConfigMapName: mysql-configmap
  mongoConfigMapName: mongo-configmap

  activeProfile: development
  configServerURL: configserver:http://configserver:14117/
  discoveryServerURL: http://spring-cloud-kubernetes-discoveryserver:80/
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/Vocasia/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-1.27.0.jar"
  otelExporterEndPoint: http://tempo-grafana-tempo-distributor:4317
  otelMetricsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092

  awsAccessKeyId: AKIA6GBMGQU2WPGRSEWD
  awsSecretAccessKey: 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
  awsS3Region: ap-southeast-1
  awsS3Bucket: vocasia

  midtransMerchantId: G831856510
  midtransClientKey: SB-Mid-client-4KbJJQfBaYS9Lplt
  midtransServerKey: SB-Mid-server-l-PGFhcZZ-wTh5bebWsEefs0
  midtransIsProduction: "false"

  authenticationApplicationName: authentication
  authenticationOtelServiceName: authentication
  authenticationMysqlRootPassword: password
  authenticationMysqlDatabase: authentication_db
  authenticationSpringDatasourceUsername: root
  authenticationSpringDatasourcePassword: password
  authenticationSpringDatasourceUrl: jdbc:mysql://db-authentication:30618/authentication_db
  authenticationEmailInDestination: send-communication
  authenticationEmailInGroup: authentication

  courseApplicationName: course
  courseOtelServiceName: course
  courseMysqlRootPassword: password
  courseMysqlDatabase: course_db
  courseSpringDatasourceUsername: root
  courseSpringDatasourcePassword: password
  courseSpringDatasourceUrl: jdbc:mysql://db-course:30620/course_db

  enrollmentApplicationName: enrollment
  enrollmentOtelServiceName: enrollment
  enrollmentMysqlRootPassword: password
  enrollmentMysqlDatabase: enrollment_db
  enrollmentSpringDatasourceUsername: root
  enrollmentSpringDatasourcePassword: password
  enrollmentSpringDatasourceUrl: jdbc:mysql://db-enrollment:30623/enrollment_db

  financeApplicationName: finance
  financeOtelServiceName: finance
  financePercentPlatformFee: 5
  financeMysqlRootPassword: password
  financeMysqlDatabase: finance_db
  financeSpringDatasourceUsername: root
  financeSpringDatasourcePassword: password
  financeSpringDatasourceUrl: jdbc:mysql://db-finance:30624/finance_db

  instructorApplicationName: instructor
  instructorOtelServiceName: instructor
  instructorMysqlRootPassword: password
  instructorMysqlDatabase: instructor_db
  instructorSpringDatasourceUsername: root
  instructorSpringDatasourcePassword: password
  instructorSpringDatasourceUrl: jdbc:mysql://db-instructor:30619/instructor_db

  orderApplicationName: order
  orderOtelServiceName: order
  orderMysqlRootPassword: password
  orderMysqlDatabase: order_db
  orderSpringDatasourceUsername: root
  orderSpringDatasourcePassword: password
  orderSpringDatasourceUrl: jdbc:mysql://db-order:30621/order_db

  paymentApplicationName: payment
  paymentOtelServiceName: payment
  paymentMysqlRootPassword: password
  paymentMysqlDatabase: payment_db
  paymentSpringDatasourceUsername: root
  paymentSpringDatasourcePassword: password
  paymentSpringDatasourceUrl: jdbc:mysql://db-payment:30622/payment_db

  qnaApplicationName: qna
  qnaOtelServiceName: qna
  qnaMysqlRootPassword: password
  qnaMysqlDatabase: qna_db
  qnaSpringDatasourceUsername: root
  qnaSpringDatasourcePassword: password
  qnaSpringDatasourceUrl: jdbc:mysql://db-qna:30625/qna_db

  catalogMongoInitDbRootUsername: root
  catalogMongoInitDbRootPassword: password
  catalogSpringDataMongodbUri: mongodb://db-catalog:30627/catalog_db
  catalogSpringDataMongodbDatabase: catalog_db

  gatewayserverApplicationName: gatewayserver
  gatewayserverOtelServiceName: gatewayserver

  keycloakAdmin: admin
  keycloakAdminPassword: admin
  keycloakLogLevel: DEBUG
  keycloakServerUrl: http://keycloak.default.svc.cluster.local:80
  keycloakClientId: vocasia-users
  keycloakClientSecret: ""
  keycloakRealm: Vocasia
  keycloakAuthClientId: vocasia-auth

  rabbitmqHost: rabbitmq.default.svc.cluster.local
  rabbitmqPort: 5672
  rabbitmqUsername: guest
  rabbitmqPassword: guest

  emailFunctionDefinition: email
  emailInDestination: send-communication
  emailInGroup: email

  defaultBinder: kafka
  redisHost: redis-master.default.svc.cluster.local
