global:
  configMapName: vocasia-configmap
  mysqlConfigMapName: mysql-configmap
  mongoConfigMapName: mongo-configmap

  activeProfile: development
  configServerURL: configserver:http://configserver:14117/
  eurekaServerURL: http://eurekaserver:14118/eureka/
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/Vocasia/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-1.27.0.jar"
  otelExporterEndPoint: http://tempo-grafana-tempo-distributor:4317
  otelMetricsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092

  awsAccessKeyId: AKIA6GBMGQU2WPGRSEWD
  awsSecretAccessKey: 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
  awsS3Region: ap-southeast-1
  awsS3Bucket: vocasia

  midtransMerchantId: G831856510
  midtransClientKey: SB-Mid-client-4KbJJQfBaYS9Lplt
  midtransServerKey: SB-Mid-server-l-PGFhcZZ-wTh5bebWsEefs0
  midtransIsProduction: "false"

  authenticationApplicationName: authentication
  authenticationOtelServiceName: authentication
  authenticationMysqlRootPassword: password
  authenticationMysqlDatabase: authentication_db
  authenticationSpringDatasourceUsername: root
  authenticationSpringDatasourcePassword: password
  authenticationSpringDatasourceUrl: jdbc:mysql://db-authentication:3306/authentication_db

  courseApplicationName: course
  courseOtelServiceName: course
  courseMysqlRootPassword: password
  courseMysqlDatabase: course_db
  courseSpringDatasourceUsername: root
  courseSpringDatasourcePassword: password
  courseSpringDatasourceUrl: jdbc:mysql://db-course:3306/course_db

  enrollmentApplicationName: enrollment
  enrollmentOtelServiceName: enrollment
  enrollmentMysqlRootPassword: password
  enrollmentMysqlDatabase: enrollment_db
  enrollmentSpringDatasourceUsername: root
  enrollmentSpringDatasourcePassword: password
  enrollmentSpringDatasourceUrl: jdbc:mysql://db-enrollment:3306/enrollment_db

  financeApplicationName: finance
  financeOtelServiceName: finance
  financePercentPlatformFee: 5
  financeMysqlRootPassword: password
  financeMysqlDatabase: finance_db
  financeSpringDatasourceUsername: root
  financeSpringDatasourcePassword: password
  financeSpringDatasourceUrl: jdbc:mysql://db-finance:3306/finance_db

  instructorApplicationName: instructor
  instructorOtelServiceName: instructor
  instructorMysqlRootPassword: password
  instructorMysqlDatabase: instructor_db
  instructorSpringDatasourceUsername: root
  instructorSpringDatasourcePassword: password
  instructorSpringDatasourceUrl: jdbc:mysql://db-instructor:3306/instructor_db

  orderApplicationName: order
  orderOtelServiceName: order
  orderMysqlRootPassword: password
  orderMysqlDatabase: order_db
  orderSpringDatasourceUsername: root
  orderSpringDatasourcePassword: password
  orderSpringDatasourceUrl: jdbc:mysql://db-order:3306/order_db

  paymentApplicationName: payment
  paymentOtelServiceName: payment
  paymentMysqlRootPassword: password
  paymentMysqlDatabase: payment_db
  paymentSpringDatasourceUsername: root
  paymentSpringDatasourcePassword: password
  paymentSpringDatasourceUrl: jdbc:mysql://db-payment:3306/payment_db

  qnaApplicationName: qna
  qnaOtelServiceName: qna
  qnaMysqlRootPassword: password
  qnaMysqlDatabase: qna_db
  qnaSpringDatasourceUsername: root
  qnaSpringDatasourcePassword: password
  qnaSpringDatasourceUrl: jdbc:mysql://db-qna:3306/qna_db

  catalogMongoInitDbRootUsername: root
  catalogMongoInitDbRootPassword: password
  catalogSpringDataMongodbUri: mongodb://db-catalog:27017/catalog_db
  catalogSpringDataMongodbDatabase: catalog_db

  gatewayserverApplicationName: gatewayserver
  gatewayserverOtelServiceName: gatewayserver

  keycloakAdmin: admin
  keycloakAdminPassword: admin
  keycloakLogLevel: DEBUG
  keycloakServerUrl: http://keycloak.default.svc.cluster.local:80
  keycloakClientId: vocasia-users
  keycloakClientSecret: "NW5Azu7Rk7Tjxps3SDuAMvBKrhKe7rkF"
  keycloakRealm: Vocasia
  keycloakAuthClientId: vocasia-auth
