deploymentName: order-deployment
serviceName: order
appLabel: order
appName: order

replicaCount: 1

hpa:
  name: order-hpa
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75

resources:
  cpu:
    request: "256m"
    limit: "512m"
  memory:
    request: "256Mi"
    limit: "512Mi"

image:
  repository: martinms20/order
  tag: cloud

containerPort: 14124

service:
  type: ClusterIP
  port: 14124
  targetPort: 14124

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
redis_enabled: true

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ORDER_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ORDER_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ORDER_SPRING_DATASOURCE_URL
  - name: FINANCE_PERCENT_PLATFORM_FEE
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: FINANCE_PERCENT_PLATFORM_FEE