deploymentName: service-order
serviceName: order
appLabel: order
appName: order

replicaCount: 1

hpa:
  name: order-hpa
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

resources:
  cpu:
    request: "500m"
    limit: "1000m"
  memory:
    request: "1Gi"
    limit: "2Gi"

image:
  repository: martinms20/order
  tag: cloud

containerPort: 8007

service:
  type: ClusterIP
  port: 8007
  targetPort: 8007

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
redis_enabled: true

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ORDER_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ORDER_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ORDER_SPRING_DATASOURCE_URL
  - name: FINANCE_PERCENT_PLATFORM_FEE
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: FINANCE_PERCENT_PLATFORM_FEE