{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapName }}
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.global.activeProfile }}"
  SPRING_CONFIG_IMPORT: "{{ .Values.global.configServerURL }}"
  SPRING.CLOUD.KUBERNETES.DISCOVERY.DISCOVERY-SERVER-URL: "{{ .Values.global.discoveryServerURL }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "{{ .Values.global.keyCloakURL }}"
  JAVA_TOOL_OPTIONS: "{{ .Values.global.openTelemetryJavaAgent }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.global.otelExporterEndPoint }}"
  OTEL_METRICS_EXPORTER: "{{ .Values.global.otelMetricsExporter }}"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "{{ .Values.global.kafkaBrokerURL }}"

  AWS_ACCESS_KEY_ID: "{{ .Values.global.awsAccessKeyId }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.global.awsSecretAccessKey }}"
  AWS_S3_REGION: "{{ .Values.global.awsS3Region }}"
  AWS_S3_BUCKET: "{{ .Values.global.awsS3Bucket }}"

  MIDTRANS_MERCHANT_ID: "{{ .Values.global.midtransMerchantId }}"
  MIDTRANS_CLIENT_KEY: "{{ .Values.global.midtransClientKey }}"
  MIDTRANS_SERVER_KEY: "{{ .Values.global.midtransServerKey }}"
  MIDTRANS_IS_PRODUCTION: "{{ .Values.global.midtransIsProduction }}"

  AUTHENTICATION_APPLICATION_NAME: "{{ .Values.global.authenticationApplicationName }}"
  AUTHENTICATION_OTEL_SERVICE_NAME: "{{ .Values.global.authenticationOtelServiceName }}"
  AUTHENTICATION_MYSQL_ROOT_PASSWORD: "{{ .Values.global.authenticationMysqlRootPassword }}"
  AUTHENTICATION_MYSQL_DATABASE: "{{ .Values.global.authenticationMysqlDatabase }}"
  AUTHENTICATION_SPRING_DATASOURCE_USERNAME: "{{ .Values.global.authenticationSpringDatasourceUsername }}"
  AUTHENTICATION_SPRING_DATASOURCE_PASSWORD: "{{ .Values.global.authenticationSpringDatasourcePassword }}"
  AUTHENTICATION_SPRING_DATASOURCE_URL: "{{ .Values.global.authenticationSpringDatasourceUrl }}"
  AUTHENTICATION_SPRING_CLOUD_STREAM_BINDINGS_EMAIL_IN_0_DESTINATION: "{{ .Values.global.authenticationEmailInDestination }}"
  AUTHENTICATION_SPRING_CLOUD_STREAM_BINDINGS_EMAIL_IN_0_GROUP: "{{ .Values.global.authenticationEmailInGroup }}"

  COURSE_APPLICATION_NAME: "{{ .Values.global.courseApplicationName }}"
  COURSE_OTEL_SERVICE_NAME: "{{ .Values.global.courseOtelServiceName }}"
  COURSE_MYSQL_ROOT_PASSWORD: "{{ .Values.global.courseMysqlRootPassword }}"
  COURSE_MYSQL_DATABASE: "{{ .Values.global.courseMysqlDatabase }}"
  COURSE_SPRING_DATASOURCE_USERNAME: "{{ .Values.global.courseSpringDatasourceUsername }}"
  COURSE_SPRING_DATASOURCE_PASSWORD: "{{ .Values.global.courseSpringDatasourcePassword }}"
  COURSE_SPRING_DATASOURCE_URL: "{{ .Values.global.courseSpringDatasourceUrl }}"

  ENROLLMENT_APPLICATION_NAME: "{{ .Values.global.enrollmentApplicationName }}"
  ENROLLMENT_OTEL_SERVICE_NAME: "{{ .Values.global.enrollmentOtelServiceName }}"
  ENROLLMENT_MYSQL_ROOT_PASSWORD: "{{ .Values.global.enrollmentMysqlRootPassword }}"
  ENROLLMENT_MYSQL_DATABASE: "{{ .Values.global.enrollmentMysqlDatabase }}"
  ENROLLMENT_SPRING_DATASOURCE_USERNAME: "{{ .Values.global.enrollmentSpringDatasourceUsername }}"
  ENROLLMENT_SPRING_DATASOURCE_PASSWORD: "{{ .Values.global.enrollmentSpringDatasourcePassword }}"
  ENROLLMENT_SPRING_DATASOURCE_URL: "{{ .Values.global.enrollmentSpringDatasourceUrl }}"

  FINANCE_APPLICATION_NAME: "{{ .Values.global.financeApplicationName }}"
  FINANCE_OTEL_SERVICE_NAME: "{{ .Values.global.financeOtelServiceName }}"
  FINANCE_PERCENT_PLATFORM_FEE: "{{ .Values.global.financePercentPlatformFee }}"
  FINANCE_MYSQL_ROOT_PASSWORD: "{{ .Values.global.financeMysqlRootPassword }}"
  FINANCE_MYSQL_DATABASE: "{{ .Values.global.financeMysqlDatabase }}"
  FINANCE_SPRING_DATASOURCE_USERNAME: "{{ .Values.global.financeSpringDatasourceUsername }}"
  FINANCE_SPRING_DATASOURCE_PASSWORD: "{{ .Values.global.financeSpringDatasourcePassword }}"
  FINANCE_SPRING_DATASOURCE_URL: "{{ .Values.global.financeSpringDatasourceUrl }}"

  INSTRUCTOR_APPLICATION_NAME: "{{ .Values.global.instructorApplicationName }}"
  INSTRUCTOR_OTEL_SERVICE_NAME: "{{ .Values.global.instructorOtelServiceName }}"
  INSTRUCTOR_MYSQL_ROOT_PASSWORD: "{{ .Values.global.instructorMysqlRootPassword }}"
  INSTRUCTOR_MYSQL_DATABASE: "{{ .Values.global.instructorMysqlDatabase }}"
  INSTRUCTOR_SPRING_DATASOURCE_USERNAME: "{{ .Values.global.instructorSpringDatasourceUsername }}"
  INSTRUCTOR_SPRING_DATASOURCE_PASSWORD: "{{ .Values.global.instructorSpringDatasourcePassword }}"
  INSTRUCTOR_SPRING_DATASOURCE_URL: "{{ .Values.global.instructorSpringDatasourceUrl }}"

  ORDER_APPLICATION_NAME: "{{ .Values.global.orderApplicationName }}"
  ORDER_OTEL_SERVICE_NAME: "{{ .Values.global.orderOtelServiceName }}"
  ORDER_MYSQL_ROOT_PASSWORD: "{{ .Values.global.orderMysqlRootPassword }}"
  ORDER_MYSQL_DATABASE: "{{ .Values.global.orderMysqlDatabase }}"
  ORDER_SPRING_DATASOURCE_USERNAME: "{{ .Values.global.orderSpringDatasourceUsername }}"
  ORDER_SPRING_DATASOURCE_PASSWORD: "{{ .Values.global.orderSpringDatasourcePassword }}"
  ORDER_SPRING_DATASOURCE_URL: "{{ .Values.global.orderSpringDatasourceUrl }}"

  PAYMENT_APPLICATION_NAME: "{{ .Values.global.paymentApplicationName }}"
  PAYMENT_OTEL_SERVICE_NAME: "{{ .Values.global.paymentOtelServiceName }}"
  PAYMENT_MYSQL_ROOT_PASSWORD: "{{ .Values.global.paymentMysqlRootPassword }}"
  PAYMENT_MYSQL_DATABASE: "{{ .Values.global.paymentMysqlDatabase }}"
  PAYMENT_SPRING_DATASOURCE_USERNAME: "{{ .Values.global.paymentSpringDatasourceUsername }}"
  PAYMENT_SPRING_DATASOURCE_PASSWORD: "{{ .Values.global.paymentSpringDatasourcePassword }}"
  PAYMENT_SPRING_DATASOURCE_URL: "{{ .Values.global.paymentSpringDatasourceUrl }}"

  QNA_APPLICATION_NAME: "{{ .Values.global.qnaApplicationName }}"
  QNA_OTEL_SERVICE_NAME: "{{ .Values.global.qnaOtelServiceName }}"
  QNA_MYSQL_ROOT_PASSWORD: "{{ .Values.global.qnaMysqlRootPassword }}"
  QNA_MYSQL_DATABASE: "{{ .Values.global.qnaMysqlDatabase }}"
  QNA_SPRING_DATASOURCE_USERNAME: "{{ .Values.global.qnaSpringDatasourceUsername }}"
  QNA_SPRING_DATASOURCE_PASSWORD: "{{ .Values.global.qnaSpringDatasourcePassword }}"
  QNA_SPRING_DATASOURCE_URL: "{{ .Values.global.qnaSpringDatasourceUrl }}"

  CATALOG_SPRING_DATA_MONGODB_URI: "{{ .Values.global.catalogSpringDataMongodbUri }}"
  CATALOG_SPRING_DATA_MONGODB_DATABASE: "{{ .Values.global.catalogSpringDataMongodbDatabase }}"
  CATALOG_MONGO_INITDB_ROOT_USERNAME: "{{ .Values.global.catalogMongoInitDbRootUsername }}"
  CATALOG_MONGO_INITDB_ROOT_PASSWORD: "{{ .Values.global.catalogMongoInitDbRootPassword }}"

  GATEWAYSERVER_APPLICATION_NAME: "{{ .Values.global.gatewayserverApplicationName }}"
  GATEWAYSERVER_OTEL_SERVICE_NAME: "{{ .Values.global.gatewayserverOtelServiceName }}"

  VOCASIA_MYSQL_ROOT_PASSWORD: "{{ .Values.global.vocasiaMysqlRootPassword }}"
  VOCASIA_MYSQL_DATABASE: "{{ .Values.global.vocasiaMysqlDatabase }}"

  KEYCLOAK_ADMIN: "{{ .Values.global.keycloakAdmin }}"
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.global.keycloakAdminPassword }}"
  KEYCLOAK_LOG_LEVEL: "{{ .Values.global.keycloakLogLevel }}"
  KEYCLOAK_SERVER_URL: "{{ .Values.global.keycloakServerUrl }}"
  KEYCLOAK_CLIENT_ID: "{{ .Values.global.keycloakClientId }}"
  KEYCLOAK_CLIENT_SECRET: "{{ .Values.global.keycloakClientSecret }}"
  KEYCLOAK_REALM: "{{ .Values.global.keycloakRealm }}"
  KEYCLOAK_AUTH_CLIENT_ID: "{{ .Values.global.keycloakAuthClientId }}"

  SPRING_RABBITMQ_HOST: "{{ .Values.global.rabbitmqHost }}"
  SPRING_RABBITMQ_PORT: "{{ .Values.global.rabbitmqPort }}"
  SPRING_RABBITMQ_USERNAME: "{{ .Values.global.rabbitmqUsername }}"
  SPRING_RABBITMQ_PASSWORD: "{{ .Values.global.rabbitmqPassword }}"
  SPRING_RABBITMQ_CONNECTION_TIMEOUT: "{{ .Values.global.rabbitmqConnectionTimeout }}"

  EMAIL_SPRING_CLOUD_FUNCTION_DEFINITION: "{{ .Values.global.emailFunctionDefinition }}"
  EMAIL_SPRING_CLOUD_STREAM_BINDINGS_EMAIL_IN_0_DESTINATION: "{{ .Values.global.emailInDestination }}"
  EMAIL_SPRING_CLOUD_STREAM_BINDINGS_EMAIL_IN_0_GROUP: "{{ .Values.global.emailInGroup }}"

  SPRING_CLOUD_STREAM_DEFAULT_BINDER: "{{ .Values.global.defaultBinder }}"
  SPRING_DATA_REDIS_HOST: "{{ .Values.global.redisHost }}"
{{- end -}}