deploymentName: service-user
serviceName: user
appLabel: user
appName: user

replicaCount: 1

hpa:
  name: user-hpa
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

resources:
  cpu:
    request: "500m"
    limit: "1000m"
  memory:
    request: "1Gi"
    limit: "2Gi"

image:
  repository: martinms20/user
  tag: cloud

containerPort: 8009

service:
  type: ClusterIP
  port: 8009
  targetPort: 8009

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
redis_enabled: false

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: USER_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: USER_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: USER_SPRING_DATASOURCE_URL
  - name: MIDTRANS_MERCHANT_ID
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: MIDTRANS_MERCHANT_ID
  - name: MIDTRANS_CLIENT_KEY
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: MIDTRANS_CLIENT_KEY
  - name: MIDTRANS_SERVER_KEY
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: MIDTRANS_SERVER_KEY
  - name: MIDTRANS_IS_PRODUCTION
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: MIDTRANS_IS_PRODUCTION