apiVersion: v1  # API version for the Service resource.
kind: Service  # Resource type: Service.
metadata:
  name: nginx-service  # Name of the Service.
spec:
  type: LoadBalancer  # Exposes the Service externally using a cloud provider's load balancer.
  selector:
    app: nginx  # Targets pods with the label `app: nginx`.
  ports:
    - protocol: TCP  # Protocol for the Service.
      port: 9000  # Port exposed by the Service.
      targetPort: 80  # Port on the container to forward traffic to.
