export const blogs = [
    {
        id: 1,
        imageSrc: "/assets/img/blog-list/1.png",
        category: "Writing",
        title: "Eco-Education in Our Lives: We Can Change the Future",
        date: "January 5, 2023",
        desc: `Our features, journey, tips and us being us. Lorem ipsum dolor sit amet, accumsan in, tempor dictum neque`,
    },
    {
        id: 2,
        imageSrc: "/assets/img/blog-list/2.png",
        category: "EDUCATION",
        title: "Engendering a culture of professional development",
        date: "February 18, 2023",
        desc: `Our features, journey, tips and us being us. Lorem ipsum dolor sit amet, accumsan in, tempor dictum neque`,
    },
    {
        id: 3,
        imageSrc: "/assets/img/blog-list/3.png",
        category: "Business",
        title: "Increasing engagement with Instagram",
        date: "March 27, 2023",
        desc: `Our features, journey, tips and us being us. Lorem ipsum dolor sit amet, accumsan in, tempor dictum neque`,
    },
    {
        id: 4,
        imageSrc: "/assets/img/blog-list/4.png",
        category: "Business",
        title: "How to design a simple, yet unique and memorable brand identity",
        date: "April 14, 2023",
        desc: `Our features, journey, tips and us being us. Lorem ipsum dolor sit amet, accumsan in, tempor dictum neque`,
    },
    {
        id: 5,
        imageSrc: "/assets/img/blog-list/5.png",
        category: "Photo & Film",
        title: "5 marketing trends that you should be prepared for in 2022",
        date: "May 22, 2023",
        desc: `Our features, journey, tips and us being us. Lorem ipsum dolor sit amet, accumsan in, tempor dictum neque`,
    },
    {
        id: 6,
        imageSrc: "/assets/img/blog-list/6.png",
        category: "Lifestyle",
        title: "8 great design trends that are making a come-back in 2021",
        date: "June 8, 2023",
        desc: `Our features, journey, tips and us being us. Lorem ipsum dolor sit amet, accumsan in, tempor dictum neque`,
    },
    {
        id: 7,
        imageSrc: "/assets/img/blog-list/7.png",
        category: "Illustration",
        title:
            "How to be more creative: 5 cool tips to find inspiration everywhere",
        date: "July 17, 2023",
        desc: `Our features, journey, tips and us being us. Lorem ipsum dolor sit amet, accumsan in, tempor dictum neque`,
    },
    {
        id: 8,
        imageSrc: "/assets/img/blog-list/8.png",
        category: "Design",
        title:
            "8 interesting programming languages you should be paying attention to",
        date: "August 3, 2023",
        desc: `Our features, journey, tips and us being us. Lorem ipsum dolor sit amet, accumsan in, tempor dictum neque`,
    },
    {
        id: 9,
        imageSrc: "/assets/img/blog-list/9.png",
        category: "Animation",
        title: "19 ways to optimize your ad marketing budget efficiently",
        date: "September 12, 2023",
        desc: `Our features, journey, tips and us being us. Lorem ipsum dolor sit amet, accumsan in, tempor dictum neque`,
    },
];

export const events = [
    {
        id: 1,
        imgSrc: "/assets/img/courses-list/1.png",
        title: "Summer School 2022",
        date: "6 April, 2022",
        location: "London, UK",
        desc: `Educational technology and mobile learning`,
        category: "Design",
        price: 450,
        preDiscount: 650,
    },
    {
        id: 2,
        imgSrc: "/assets/img/courses-list/2.png",
        title: "Summer School 2022",
        date: "6 April, 2022",
        location: "London, UK",
        desc: `We are changing the way the world learns`,
        category: "Animation",
        price: 450,
        preDiscount: 650,
    },
    {
        id: 3,
        imgSrc: "/assets/img/courses-list/3.png",
        title: "Summer School 2022",
        date: "6 April, 2022",
        location: "London, UK",
        desc: `Guide to visas and funding to study in the UK`,
        category: "Writing",
        price: 450,
        preDiscount: 650,
    },
    {
        id: 4,
        imgSrc: "/assets/img/courses-list/4.png",
        title: "Summer School 2022",
        date: "6 April, 2022",
        location: "London, UK",
        desc: `Achieving Advanced in Insights with Big`,
        category: "Business",
        price: 450,
        preDiscount: 650,
    },
    {
        id: 5,
        imgSrc: "/assets/img/courses-list/5.png",
        title: "Summer School 2022",
        date: "6 April, 2022",
        location: "London, UK",
        desc: `Educational technology and mobile learning`,
        category: "Photo & Film",
        price: 450,
        preDiscount: 650,
    },
    {
        id: 6,
        imgSrc: "/assets/img/courses-list/6.png",
        title: "Summer School 2022",
        date: "6 April, 2022",
        location: "London, UK",
        desc: `We are changing the way the world learns`,
        category: "Lifestyle",
        price: 450,
        preDiscount: 650,
    },
    {
        id: 7,
        imgSrc: "/assets/img/courses-list/7.png",
        title: "Summer School 2022",
        date: "6 April, 2022",
        location: "London, UK",
        desc: `We are changing the way the world learns`,
        category: "Illustration",
        price: 450,
        preDiscount: 650,
    },
    {
        id: 8,
        imgSrc: "/assets/img/courses-list/8.png",
        title: "Summer School 2022",
        date: "6 April, 2022",
        location: "London, UK",
        desc: `We are changing the way the world learns`,
        category: "Design",
        price: 450,
        preDiscount: 650,
    },
    {
        id: 9,
        imgSrc: "/assets/img/courses-list/9.png",
        title: "Summer School 2022",
        date: "6 April, 2022",
        location: "London, UK",
        desc: `We are changing the way the world learns`,
        category: "Animation",
        price: 450,
        preDiscount: 650,
    },
];