app:
  version: 1.0.0
  name: "Finance Service"
  environment: "development"

finance:
  percent_platform_fee: 5

aws:
  access_key_id: "AKIA6GBMGQU2WPGRSEWD"
  secret_access_key: "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"
  s3:
    region: "ap-southeast-1"
    bucket: "vocasia"
