deploymentName: service-instructor
serviceName: instructor
appLabel: instructor
appName: instructor

replicaCount: 1

hpa:
  name: instructor-hpa
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

resources:
  cpu:
    request: "500m"
    limit: "2"
  memory:
    request: "500Mi"
    limit: "2Gi"

image:
  repository: martinms20/instructor
  tag: cloud-1.0.0

containerPort: 8007

service:
  type: ClusterIP
  port: 8007
  targetPort: 8007

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
rabbit_enabled: false
redis_enabled: true

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: INSTRUCTOR_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: INSTRUCTOR_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: INSTRUCTOR_SPRING_DATASOURCE_URL
