services:
  network-deploy-service:
    networks:
      - vocasia

  base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  service-config:
    extends:
      service: base-config
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: redis
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8072/eureka/"
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-1.27.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_METRICS_EXPORTER: none

  service-aws-config:
    extends:
      service: service-config
    environment:
      AWS_ACCESS_KEY_ID: "AKIA6GBMGQU2WPGRSEWD"
      AWS_SECRET_ACCESS_KEY: "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"
      AWS_S3_REGION: "ap-southeast-1"
      AWS_S3_BUCKET: "vocasia"
