services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: app-keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_LOG_LEVEL: "DEBUG"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service

  db_authentication:
    image: mysql:8.0
    container_name: db-authentication
    ports:
      - "30618:3306"
    environment:
      MYSQL_DATABASE: authentication_db
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    volumes:
      - authentication_db_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: base-config

  db_instructor:
    image: mysql:8.0
    container_name: db-instructor
    ports:
      - "30619:3306"
    environment:
      MYSQL_DATABASE: instructor_db
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    volumes:
      - instructor_db_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: base-config

  db_course:
    image: mysql:8.0
    container_name: db-course
    ports:
      - "30620:3306"
    environment:
      MYSQL_DATABASE: course_db
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    volumes:
      - course_db_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: base-config

  db_order:
    image: mysql:8.0
    container_name: db-order
    ports:
      - "30621:3306"
    environment:
      MYSQL_DATABASE: order_db
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    volumes:
      - order_db_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: base-config

  db_payment:
    image: mysql:8.0
    container_name: db-payment
    ports:
      - "30622:3306"
    environment:
      MYSQL_DATABASE: payment_db
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    volumes:
      - payment_db_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: base-config

  db_enrollment:
    image: mysql:8.0
    container_name: db-enrollment
    ports:
      - "30623:3306"
    environment:
      MYSQL_DATABASE: enrollment_db
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    volumes:
      - enrollment_db_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: base-config

  configserver:
    image: martinms20/configserver:v1.0.0
    container_name: config-server
    ports:
      - "14117:14117"
    healthcheck:
      test: "curl --fail --silent localhost:14117/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    extends:
      file: common-config.yml
      service: base-config

  eurekaserver:
    image: "martinms20/eurekaserver:v1.0.0"
    container_name: eureka-server
    ports:
      - "14118:14118"
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:14118/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    extends:
      file: common-config.yml
      service: base-config

  authentication_service:
    image: martinms20/authentication:v1.0.0
    container_name: service-authentication
    ports:
      - "14120:14120"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      SPRING_DATASOURCE_URL: jdbc:mysql://db-authentication:3306/authentication_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
      KEYCLOACK_SERVER_URL: "http://keycloak:8080"
      KEYCLOACK_CLIENT_ID: "vocasia-users"
      KEYCLOACK_CLIENT_SECRET: "fr8AziJmAQZ8Yi7gL396qticjOHvzxGt"
      KEYCLOACK_REALM: "Vocasia"
      KEYCLOACK_AUTH_CLIENT_ID: "vocasia-auth"
      AWS_ACCESS_KEY_ID: "AKIA6GBMGQU2WPGRSEWD"
      AWS_SECRET_ACCESS_KEY: "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"
      AWS_S3_REGION: "ap-southeast-1"
      AWS_S3_BUCKET: "vocasia"
    healthcheck:
      test: "curl --fail --silent localhost:14120/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    depends_on:
      db_authentication:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config

  instructor_service:
    image: martinms20/instructor:v1.0.0
    container_name: service-instructor
    ports:
      - "14121:14121"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      SPRING_DATASOURCE_URL: jdbc:mysql://db-instructor:3306/instructor_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
    healthcheck:
      test: "curl --fail --silent localhost:14121/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    depends_on:
      db_instructor:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config

  course_service:
    image: martinms20/course:v1.0.0
    container_name: service-course
    ports:
      - "14122:14122"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      SPRING_DATASOURCE_URL: jdbc:mysql://db-course:3306/course_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
      AWS_ACCESS_KEY_ID: "AKIA6GBMGQU2WPGRSEWD"
      AWS_SECRET_ACCESS_KEY: "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"
      AWS_S3_REGION: "ap-southeast-1"
      AWS_S3_BUCKET: "vocasia"
    healthcheck:
      test: "curl --fail --silent localhost:14122/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    depends_on:
      db_course:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config

  order_service:
    image: martinms20/order:v1.0.0
    container_name: service-order
    ports:
      - "14124:14124"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      SPRING_DATASOURCE_URL: jdbc:mysql://db-order:3306/order_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
    healthcheck:
      test: "curl --fail --silent localhost:14124/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    depends_on:
      db_order:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config

  payment_service:
    image: martinms20/payment:v1.0.0
    container_name: service-payment
    ports:
      - "14125:14125"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      SPRING_DATASOURCE_URL: jdbc:mysql://db-payment:3306/payment_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
      MIDTRANS_MERCHANT_ID: "G831856510"
      MIDTRANS_CLIENT_KEY: "SB-Mid-client-4KbJJQfBaYS9Lplt"
      MIDTRANS_SERVER_KEY: "SB-Mid-server-l-PGFhcZZ-wTh5bebWsEefs0"
      MIDTRANS_IS_PRODUCTION: false
    healthcheck:
      test: "curl --fail --silent localhost:14125/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    depends_on:
      db_payment:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config

  enrollment_service:
    image: martinms20/enrollment:v1.0.0
    container_name: service-enrollment
    ports:
      - "14126:14126"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      SPRING_DATASOURCE_URL: jdbc:mysql://db-enrollment:3306/enrollment_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
    healthcheck:
      test: "curl --fail --silent localhost:14126/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 20s
    depends_on:
      db_enrollment:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config

  playground_service:
    image: martinms20/playground:v1.0.0
    container_name: service-playground
    ports:
      - "14123:14123"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
      KEYCLOACK_SERVER: "INI DOCKER COMPOSE"
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config

  gatewayserver:
    image: "martinms20/gatewayserver:v1.0.0"
    container_name: gateway-server
    ports:
      - "14119:14119"
    depends_on:
      eurekaserver:
        condition: service_healthy
      authentication_service:
        condition: service_healthy
      instructor_service:
        condition: service_healthy
      course_service:
        condition: service_healthy
      order_service:
        condition: service_healthy
      payment_service:
        condition: service_healthy
      enrollment_service:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://app-keycloak:8080/realms/Vocasia/protocol/openid-connect/certs"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
    extends:
      file: common-config.yml
      service: base-config

networks:
  vocasia:
    driver: bridge

volumes:
  authentication_db_data:
    driver: local
  instructor_db_data:
    driver: local
  course_db_data:
    driver: local
  order_db_data:
    driver: local
  payment_db_data:
    driver: local
  enrollment_db_data:
    driver: local
