services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: app-keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_LOG_LEVEL: "DEBUG"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service

  db_authentication:
    image: mysql:8.0
    container_name: db-authentication
    ports:
      - "30618:3306"
    environment:
      MYSQL_DATABASE: authentication_db
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - authentication_db_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: base-config

  db_instructor:
    image: mysql:8.0
    container_name: db-instructor
    ports:
      - "30619:3306"
    environment:
      MYSQL_DATABASE: instructor_db
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - instructor_db_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: base-config

  db_course:
    image: mysql:8.0
    container_name: db-course
    ports:
      - "30620:3306"
    environment:
      MYSQL_DATABASE: course_db
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - course_db_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: base-config

  configserver:
    image: martinms20/configserver:v1.0.0
    container_name: config-server
    ports:
      - "14117:14117"
    healthcheck:
      test: "curl --fail --silent localhost:14117/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: base-config

  eurekaserver:
    image: "martinms20/eurekaserver:v1.0.0"
    container_name: eureka-server
    ports:
      - "14118:14118"
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:14118/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: base-config

  authentication_service:
    image: martinms20/authentication:v1.0.0
    container_name: service-authentication
    ports:
      - "14120:14120"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      SPRING_DATASOURCE_URL: jdbc:mysql://db-authentication:3306/authentication_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
      KEYCLOACK_SERVER_URL: "http://keycloak:8080"
      KEYCLOACK_CLIENT_ID: "vocasia-users"
      KEYCLOACK_CLIENT_SECRET: "fr8AziJmAQZ8Yi7gL396qticjOHvzxGt"
      KEYCLOACK_REALM: "Vocasia"
      KEYCLOACK_AUTH_CLIENT_ID: "vocasia-auth"
    healthcheck:
      test: "curl --fail --silent localhost:14120/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      db_authentication:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config

  instructor_service:
    image: martinms20/instructor:v1.0.0
    container_name: service-instructor
    ports:
      - "14121:14121"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      SPRING_DATASOURCE_URL: jdbc:mysql://db-instructor:3306/instructor_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
    healthcheck:
      test: "curl --fail --silent localhost:14121/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      db_instructor:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config

  course_service:
    image: martinms20/course:v1.0.0
    container_name: service-course
    ports:
      - "14122:14122"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      SPRING_DATASOURCE_URL: jdbc:mysql://db-course:3306/course_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
    healthcheck:
      test: "curl --fail --silent localhost:14122/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      db_course:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config

  playground_service:
    image: martinms20/playground:v1.0.0
    container_name: service-playground
    ports:
      - "14123:14123"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
      KEYCLOACK_SERVER: "INI DOCKER COMPOSE"
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config

  gatewayserver:
    image: "martinms20/gatewayserver:v1.0.0"
    container_name: gateway-server
    ports:
      - "14119:14119"
    depends_on:
      eurekaserver:
        condition: service_healthy
      authentication_service:
        condition: service_healthy
      instructor_service:
        condition: service_healthy
      course_service:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:14117/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:14118/eureka/"
    extends:
      file: common-config.yml
      service: base-config

networks:
  vocasia:
    driver: bridge

volumes:
  authentication_db_data:
    driver: local
  instructor_db_data:
    driver: local
  course_db_data:
    driver: local