deploymentName: db-vocasia-mongo
serviceName: db-vocasia-mongo
appLabel: db-vocasia-mongo
appName: db-vocasia-mongo

replicaCount: 1

image:
  repository: mongo
  tag: 6.0

containerPort: 30627

service:
  port: 30627

pvc:
  name: vocasia-mongo-pvc

customEnvs:
  - name: MONGO_INITDB_ROOT_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: VOCASIA_MONGO_INITDB_ROOT_USERNAME
  - name: MONGO_INITDB_ROOT_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: VOCASIA_MONGO_INITDB_ROOT_PASSWORD