deploymentName: configserver-deployment
serviceName: configserver
appLabel: configserver
appName: configserver

replicaCount: 1

image:
  repository: martinms20/configserver
  tag: v1.0.0

containerPort: 14117

service:
  type: ClusterIP
  port: 14117
  targetPort: 14117

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
