deploymentName: enrollment-deployment
serviceName: enrollment
appLabel: enrollment
appName: enrollment

hpaLabel: enrollment-hpa
hpaCpuUtilization: 50

memoryRequest: 512Mi
cpuRequest: 256m

memoryLimit: 1024Mi
cpuLimit: 512m

replicaCount: 2
maxReplicas: 5

image:
  repository: martinms20/enrollment
  tag: v1.1.0

containerPort: 14126

service:
  type: ClusterIP
  port: 14126
  targetPort: 14126

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false # nanti ubah ke true

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ENROLLMENT_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ENROLLMENT_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ENROLLMENT_SPRING_DATASOURCE_URL