apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-order
  labels:
    app: db-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-order
  template:
    metadata:
      labels:
        app: db-order
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: ORDER_MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: ORDER_MYSQL_DATABASE
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: order-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-order
spec:
  selector:
    app: db-order
  ports:
    - protocol: TCP
      port: 30621
      targetPort: 3306
  type: LoadBalancer
