apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-catalog
  labels:
    app: db-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-catalog
  template:
    metadata:
      labels:
        app: db-catalog
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: CATALOG_MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: CATALOG_MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: CATALOG_MONGO_INITDB_DATABASE
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: catalog-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-catalog
spec:
  selector:
    app: db-catalog
  ports:
    - protocol: TCP
      port: 30627
      targetPort: 27017
  type: LoadBalancer
