apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: course-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-course
  labels:
    app: db-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-course
  template:
    metadata:
      labels:
        app: db-course
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: COURSE_MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: vocasia-configmap
                  key: COURSE_MYSQL_DATABASE
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: course-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-course
spec:
  selector:
    app: db-course
  ports:
    - protocol: TCP
      port: 30620
      targetPort: 3306
  type: LoadBalancer
