deploymentName: instructor-deployment
serviceName: instructor
appLabel: instructor
appName: instructor

hpaLabel: instructor-hpa
hpaCpuUtilization: 50

memoryRequest: 128Mi
cpuRequest: 256m

memoryLimit: 256Mi
cpuLimit: 512m

replicaCount: 2
maxReplicas: 5

image:
  repository: martinms20/instructor
  tag: v1.1.0

containerPort: 14121

service:
  type: ClusterIP
  port: 14121
  targetPort: 14121

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: INSTRUCTOR_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: INSTRUCTOR_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: INSTRUCTOR_SPRING_DATASOURCE_URL