deploymentName: service-gatewayserver
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

hpa:
  name: gatewayserver-hpa
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90

resources:
  cpu:
    request: "500m"
    limit: "1000m"
  memory:
    request: "1Gi"
    limit: "2Gi"

image:
  repository: martinms20/gatewayserver
  tag: cloud

containerPort: 14119

service:
  type: LoadBalancer
  port: 14119
  targetPort: 14119

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: false
