deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: martinms20/gatewayserver
  tag: cloud

containerPort: 14119

service:
  type: LoadBalancer
  port: 14119
  targetPort: 14119

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: false
