deploymentName: service-gatewayserver
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

hpa:
  name: gatewayserver-hpa
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

resources:
  cpu:
    request: "250m"
    limit: "500m"
  memory:
    request: "250Mi"
    limit: "500Mi"

image:
  repository: martinms20/gatewayserver
  tag: cloud-1.0.1

containerPort: 8073

service:
  type: LoadBalancer
  port: 8073
  targetPort: 8073

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: false
rabbit_enabled: false
redis_enabled: false
