deploymentName: authentication-deployment
serviceName: authentication
appLabel: authentication
appName: authentication

hpaLabel: authentication-hpa
hpaCpuUtilization: 50

memoryRequest: 512Mi
cpuRequest: 256m

memoryLimit: 1024Mi
cpuLimit: 512m

replicaCount: 2
maxReplicas: 5

image:
  repository: martinms20/authentication
  tag: v1.1.0

containerPort: 14120

service:
  type: ClusterIP
  port: 14120
  targetPort: 14120

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false # nanti ubah ke true

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_SPRING_DATASOURCE_URL
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_S3_REGION
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_S3_REGION
  - name: AWS_S3_BUCKET
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_S3_BUCKET
  - name: KEYCLOAK_SERVER_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_SERVER_URL
  - name: KEYCLOAK_CLIENT_ID
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_CLIENT_ID
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_CLIENT_SECRET
  - name: KEYCLOAK_REALM
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_REALM
  - name: KEYCLOAK_AUTH_CLIENT_ID
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_AUTH_CLIENT_ID
