deploymentName: db-order
serviceName: db-order
appLabel: db-order
appName: db-order

replicaCount: 1

image:
  repository: mysql
  tag: 8.0

containerPort: 30621

service:
  port: 30621

pvc:
  name: order-pvc