app:
  version: 1.0.0
  name: "Authentication Service"
  environment: "development"

keycloack:
  server_url: "http://localhost:7080"
  client_id: "vocasia-users"
  client_secret: "fr8AziJmAQZ8Yi7gL396qticjOHvzxGt"
  realm: "Vocasia"
  auth_client_id: "vocasia-auth"

security:
  salt: "salt"

default:
  admin:
    username: "admin"
    password: "password"
    email: "admin@local.test"
