deploymentName: app-configserver
serviceName: configserver
appLabel: configserver
appName: configserver

replicaCount: 1

resources:
  cpu:
    request: "500m"
    limit: "1000m"
  memory:
    request: "1Gi"
    limit: "2Gi"

image:
  repository: martinms20/configserver
  tag: cloud

containerPort: 8071

service:
  type: ClusterIP
  port: 8071
  targetPort: 8071

appname_enabled: true
profile_enabled: false
config_enabled: false
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
