deploymentName: db-enrollment
serviceName: db-enrollment
appLabel: db-enrollment
appName: db-enrollment

replicaCount: 1

image:
  repository: mysql
  tag: 8.0

containerPort: 30623

service:
  port: 30623

pvc:
  name: enrollment-pvc
  
customEnvs:
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ENROLLMENT_MYSQL_ROOT_PASSWORD
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ENROLLMENT_MYSQL_DATABASE