deploymentName: authentication-deployment
serviceName: authentication
appLabel: authentication
appName: authentication

replicaCount: 1

hpa:
  name: authentication-hpa
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75

resources:
  cpu:
    request: "256m"
    limit: "512m"
  memory:
    request: "256Mi"
    limit: "512Mi"

image:
  repository: martinms20/authentication
  tag: cloud

containerPort: 14120

service:
  type: ClusterIP
  port: 14120
  targetPort: 14120

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true
redis_enabled: false

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_SPRING_DATASOURCE_URL
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_S3_REGION
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_S3_REGION
  - name: AWS_S3_BUCKET
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_S3_BUCKET
  - name: KEYCLOAK_SERVER_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_SERVER_URL
  - name: KEYCLOAK_CLIENT_ID
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_CLIENT_ID
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_CLIENT_SECRET
  - name: KEYCLOAK_REALM
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_REALM
  - name: KEYCLOAK_AUTH_CLIENT_ID
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_AUTH_CLIENT_ID
  - name: SPRING_RABBITMQ_HOST
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: SPRING_RABBITMQ_HOST
  - name: SPRING_RABBITMQ_PORT
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: SPRING_RABBITMQ_PORT
  - name: SPRING_RABBITMQ_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: SPRING_RABBITMQ_USERNAME
  - name: SPRING_RABBITMQ_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: SPRING_RABBITMQ_PASSWORD
  - name: SPRING_RABBITMQ_CONNECTION_TIMEOUT
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: SPRING_RABBITMQ_CONNECTION_TIMEOUT
  - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
  - name: SPRING_CLOUD_STREAM_DEFAULT_BINDER
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: SPRING_CLOUD_STREAM_DEFAULT_BINDER
  - name: SPRING_CLOUD_STREAM_BINDINGS_COMMUNICATION_OUT_0_DESTINATION
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_SPRING_CLOUD_STREAM_BINDINGS_EMAIL_IN_0_DESTINATION
  - name: SPRING_CLOUD_STREAM_BINDINGS_COMMUNICATION_OUT_0_GROUP
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_SPRING_CLOUD_STREAM_BINDINGS_EMAIL_IN_0_GROUP