deploymentName: service-authentication
serviceName: authentication
appLabel: authentication
appName: authentication

replicaCount: 1

hpa:
  name: authentication-hpa
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

resources:
  cpu:
    request: "700m"
    limit: "1"
  memory:
    request: "300Mi"
    limit: "500Mi"
#  cpu:
#    request: "1.4"
#    limit: "2"
#  memory:
#    request: "600Mi"
#    limit: "1Gi"

image:
  repository: martinms20/authentication
  tag: cloud-1.0.0

containerPort: 8001

service:
  type: ClusterIP
  port: 8001
  targetPort: 8001

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: true
redis_enabled: true
kafka_enabled: false
rabbit_enabled: true

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AUTHENTICATION_SPRING_DATASOURCE_URL
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_S3_REGION
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_S3_REGION
  - name: AWS_S3_BUCKET
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_S3_BUCKET
  - name: KEYCLOAK_SERVER_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_SERVER_URL
  - name: KEYCLOAK_CLIENT_ID
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_CLIENT_ID
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_CLIENT_SECRET
  - name: KEYCLOAK_REALM
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_REALM
  - name: KEYCLOAK_AUTH_CLIENT_ID
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: KEYCLOAK_AUTH_CLIENT_ID
