deploymentName: finance-deployment
serviceName: finance
appLabel: finance
appName: finance

hpaLabel: finance-hpa
hpaCpuUtilization: 50

memoryRequest: 128Mi
cpuRequest: 256m

memoryLimit: 256Mi
cpuLimit: 512m

replicaCount: 2
maxReplicas: 5

image:
  repository: martinms20/finance
  tag: v1.1.0

containerPort: 14127

service:
  type: ClusterIP
  port: 14127
  targetPort: 14127

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false

customEnvs:
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ENROLLMENT_SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ENROLLMENT_SPRING_DATASOURCE_PASSWORD
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ENROLLMENT_SPRING_DATASOURCE_URL
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_S3_REGION
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_S3_REGION
  - name: AWS_S3_BUCKET
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: AWS_S3_BUCKET
  - name: FINANCE_PERCENT_PLATFORM_FEE
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: FINANCE_PERCENT_PLATFORM_FEE