deploymentName: db-order
serviceName: db-order
appLabel: db-order
appName: db-order

replicaCount: 1

image:
  repository: mysql
  tag: 8.0

containerPort: 3311

service:
  port: 3311

pvc:
  name: order-db-pvc

customEnvs:
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ORDER_MYSQL_ROOT_PASSWORD
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        name: vocasia-configmap
        key: ORDER_MYSQL_DATABASE
